apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-sample
  labels:
    app: resume-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-sample
  template:
    metadata:
      labels:
        app: resume-sample
    spec:
      containers:
        - name: resume-sample
          image: 718511862771.dkr.ecr.us-east-2.amazonaws.com/resume-sample:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
